### ISSUE TITLE
[Suggestion] [建议] 完善 About 信息 / Fill the information in the About Section

### ISSUE THREAD

**Issue by BenjaminPan61618** [aenf23/aenf23.github.io#1]
You can add more detailed information of your repo. There is an About section, and in this section lies a gear button through which you can add more descriptions. 
你可以给这个仓库添加一些信息。在仓库主页的网页右侧侧边栏有一个“About”，旁边有一个齿轮图标，在这里，你可以完善一些信息
Description 描述: A brief introduction to your own project. (对你的项目的简要介绍)
Website 网页: Just fill in "https://aenf.github.io", and this can make a shortcut for others to get into your own project website. (就填写 "https://aenf23.github.io", 这样可以方便更多的人通过仓库点进你的项目)
Topics 关键词: You can fill in several key words to describe your project using space to separate them. (你可以给你的项目用一些关键词进行描述，注意用空格分割)

**Comment by aenf23** [comment]
good idea
